name: "文本建議/Suggestion"
description: 發表文本翻譯/修改建議。(Give editing/translation suggestions.)
title: "[Suggestion] 請使用與內容直接相關且詳細的標題"
labels: ["文本建議/suggestion"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: "我已確認："
      options:
        - label: "Issues 頁面中沒有尚為 Open 的相關主題。"
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: "我的建議："
      description: 輸入與問題直接相關且詳細的文字敘述，盡量勿只有圖片以便以文字搜尋。
    validations:
      required: true
      
